startup_inputs = {
    "L_L": {
        "Company": "QuickDoc AI",
        "Year": "2023",
        "Location": "Manila, Philippines",
        "Vision": "Make doctor appointments faster.",
        "ProblemProductFit": "Appointments are hard, so we made them easier.",
        "CompetitiveAdvantage": "It's easy to use.",
        "Team": "Team has 4 people.",
        "GoToMarket": "Uploading app to app store.",
        "CustomerUnderstanding": "People who don’t like waiting at clinics.",
        "FinancialReadiness": "No info yet.",
        "ScalabilityPotential": "Want to grow.",
        "TractionKPIs": "100 users",
        "FundraisingPreparedness": "No funding yet, but want money."
    },
    "L_M": {
        "Company": "QuickDoc AI",
        "Year": "2023",
        "Location": "Manila, Philippines",
        "Vision": "Empowering Filipinos with faster clinic booking.",
        "ProblemProductFit": "Booking at local clinics is still manual. QuickDoc AI offers a mobile-first appointment tool. However, adoption is limited due to clinic resistance.",
        "CompetitiveAdvantage": "Basic AI bot helps with clinic FAQ.",
        "Team": "Founder with design background; 3 developers. No domain expert.",
        "GoToMarket": "Trying partnerships with small clinics but few responses so far.",
        "CustomerUnderstanding": "Younger patients who dislike calling clinics.",
        "FinancialReadiness": "Not yet fundraising. Limited revenue plans.",
        "ScalabilityPotential": "Early idea for clinic-side dashboard.",
        "TractionKPIs": "300 downloads, 50 MAUs.",
        "FundraisingPreparedness": "Not yet structured."
    },
    "L_H": {
        "Company": "QuickDoc AI",
        "Year": "2023",
        "Location": "Manila, Philippines",
        "Vision": "Redefining access to care for underserved urban clinics.",
        "ProblemProductFit": "Despite digital penetration, low-income urban clinics remain offline. QuickDoc AI aims to digitize bookings, but clinic-side software is not yet functional.",
        "CompetitiveAdvantage": "Chatbot triage concept still in alpha; unique UI for elderly usability.",
        "Team": "Two junior engineers, one UX designer, and a non-technical CEO. No medical advisors yet.",
        "GoToMarket": "Plans to trial with 2 NGOs running free clinics.",
        "CustomerUnderstanding": "User research on 20 patients; many hesitant to use apps for health.",
        "FinancialReadiness": "Basic cost model designed; no revenue yet.",
        "ScalabilityPotential": "Low, pending clinic-side buy-in.",
        "TractionKPIs": "150 monthly users on mobile app; 1 clinic in early discussion.",
        "FundraisingPreparedness": "Considering angel round but not ready."
    },
    "M_L": {
        "Company": "HealBridge",
        "Year": "2021",
        "Location": "Hanoi, Vietnam",
        "Vision": "Healthcare connection made smart.",
        "ProblemProductFit": "Booking is messy so we made a platform.",
        "CompetitiveAdvantage": "Easy to use.",
        "Team": "Founder studied medicine.",
        "GoToMarket": "Planning to advertise on social media.",
        "CustomerUnderstanding": "People who go to the doctor.",
        "FinancialReadiness": "No data.",
        "ScalabilityPotential": "Will try other cities.",
        "TractionKPIs": "Some downloads.",
        "FundraisingPreparedness": "Wants investment."
    },
    "M_M": {
        "Company": "HealBridge",
        "Year": "2021",
        "Location": "Hanoi, Vietnam",
        "Vision": "Connecting clinics and patients with ease.",
        "ProblemProductFit": "Scheduling in secondary cities is inefficient. HealBridge offers a portal with clinic slots and availability.",
        "CompetitiveAdvantage": "Low-cost AI-based triage questionnaire for patients.",
        "Team": "Founder is a former public health officer. Team includes 4 developers and 1 designer.",
        "GoToMarket": "Collaborations with private hospitals are underway.",
        "CustomerUnderstanding": "Users aged 30–50 in Tier 2 cities.",
        "FinancialReadiness": "Initial revenue from paid pilots.",
        "ScalabilityPotential": "Back-end architecture supports multi-region scaling.",
        "TractionKPIs": "~6,000 users; 5 clinic partners.",
        "FundraisingPreparedness": "Planning $300K seed round."
    },
    "M_H": {
        "Company": "HealBridge",
        "Year": "2021",
        "Location": "Hanoi, Vietnam",
        "Vision": "Powering Vietnam’s connected care ecosystem.",
        "ProblemProductFit": "Fragmented scheduling across clinics in growing cities wastes patient time. HealBridge’s AI-based portal suggests slots and dynamically manages overbooking.",
        "CompetitiveAdvantage": "AI triage + multilingual intake forms.",
        "Team": "CEO: former national health service official. CTO: ex-VNG backend lead.",
        "GoToMarket": "Rolling out via NGO clinics and major lab chains.",
        "CustomerUnderstanding": "Pain points validated via interviews and A/B-tested intake.",
        "FinancialReadiness": "Earned $5K in Q1. Break-even at 12K MAUs.",
        "ScalabilityPotential": "Strong localization pipeline.",
        "TractionKPIs": "12 clinics signed. 70% retention rate.",
        "FundraisingPreparedness": "Pre-seed secured, now prepping for Seed."
    },
    "H_L": {
        "Company": "VitaLink AI",
        "Year": "2020",
        "Location": "Jakarta, Indonesia",
        "Vision": "Smarter care for Southeast Asia.",
        "ProblemProductFit": "Hospitals are crowded. We made an app.",
        "CompetitiveAdvantage": "Uses AI.",
        "Team": "Big team.",
        "GoToMarket": "Launch in big cities.",
        "CustomerUnderstanding": "People who go to hospital.",
        "FinancialReadiness": "Raised money.",
        "ScalabilityPotential": "Many markets.",
        "TractionKPIs": "Growing.",
        "FundraisingPreparedness": "Seed done."
    },
    "H_M": {
        "Company": "VitaLink AI",
        "Year": "2020",
        "Location": "Jakarta, Indonesia",
        "Vision": "Transforming healthcare access with intelligent systems.",
        "ProblemProductFit": "Overcrowded hospitals and inefficient front desks limit care. VitaLink uses AI to route patients, reduce load, and enable virtual queues.",
        "CompetitiveAdvantage": "Proprietary queue prediction + EMR sync.",
        "Team": "10+ team with former Go-Jek, Halodoc talent.",
        "GoToMarket": "Integrated with top 3 EMRs in Indonesia.",
        "CustomerUnderstanding": "Users in Jakarta, aged 20–50.",
        "FinancialReadiness": "Raised $500K seed; Series A incoming.",
        "ScalabilityPotential": "Cross-border scaling pipeline ready.",
        "TractionKPIs": "MRR $12K; 40,000 MAUs",
        "FundraisingPreparedness": "Deck + model ready. VCs in talks."
    },
    "H_H": {
        "Company": "VitaLink AI",
        "Year": "2020",
        "Location": "Jakarta, Indonesia",
        "Vision": "Rebuilding Southeast Asia’s patient experience through smart coordination.",
        "ProblemProductFit": "In Southeast Asia, patient bottlenecks at the clinic front desk cause inefficiencies and poor experiences. VitaLink AI predicts clinic queue patterns and routes patients via real-time updates. In live deployment across 60 clinics, average waiting time dropped 36%.",
        "CompetitiveAdvantage": "Proprietary wait-time AI, regional EMR partnerships, and adaptive multilingual interface.",
        "Team": "Founding team includes AI engineer from Grab, PM from Halodoc, and clinician advisor from Siloam.",
        "GoToMarket": "First wave via EMR resellers and HMO networks. Cross-sell through diagnostic labs.",
        "CustomerUnderstanding": "50+ patient interviews shaped routing model.",
        "FinancialReadiness": "Burn $18K/mo, MRR $14K. Seed completed.",
        "ScalabilityPotential": "Expansion to Philippines, Malaysia, Vietnam in 2025.",
        "TractionKPIs": "- 60 clinics live\n- 40,000 MAUs\n- 18% reduction in no-show\n- 2 B2B integrations",
        "FundraisingPreparedness": "Series A targeting $2M. Full data room ready."
    }
}